version: "3.9"
services:
  hypervit_view_assets:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hypervit/view/assets
    container_name: hypervit_view_assets
    working_dir: /home/node/app
    volumes:
      - ./components:/home/node/app/components
      - ./islands:/home/node/app/islands
      - ./public:/home/node/app/public
      - ./views:/home/node/app/views
      - ./config/tailwind/tailwind.config.ts:/home/node/app/tailwind.config.ts
